name: Build Turnip

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:sid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y bash zip

      - name: Run build script
        run: |
          chmod +x turnip-aarch64-linux.sh
          ./turnip-aarch64-linux.sh

      - name: Upload generated ZIP files
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: "*.zip"
          if-no-files-found: error
