name: Turnip adrenotools

on:
 workflow_dispatch:

permissions:
  contents: write

env:
  API_VER: 35
  BUILD_VARIANT: p2
  
jobs:
  build:
    runs-on: ubuntu-26.04-arm

    container:
      image: debian:sid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
         apt update && apt install sudo && chmod +x Build-turnip.sh
          ./Build-turnip.sh

      - name: Debug zip output
        run: |
          find turnip_workdir -type f -name "*.zip" -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: turnip_workdir/turnip/*.zip
          if-no-files-found: error

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: |
            ## GPU Support

            - **6xx**: Any. Supported by upstream Turnip.
            - **7xx**: Any. Supported by upstream Turnip and a couple of hacks.
            - **8xx**: 810 / 825 / 829 / 830 / 840. Supported by upstream Turnip (originally by patches).

            
            ## Thanks ❤️

            - **Whitebelyash**
            - **Vauzi-17**
            - **Winnative-devs**
            
          files: turnip_workdir/turnip/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
