name: Turnip experimental build 

on:
 workflow_dispatch:
 push:
  branches:
  - main
  paths:
  - "Build-turnip.sh"
  
env:
 API_VER: 35
 BUILD_VARIANT: p2
 DEBIAN_FRONTEND: non-interactive

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    container:
      image: debian:sid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
         apt update -y && apt install sudo -y && bash Build-turnip.sh

      - name: Debug zip output
        run: |
          find turnip_workdir -type f -name "*.zip" -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: turnip_workdir/turnip/*.zip
          if-no-files-found: error
